version: '3'
services:
  db:
    image: mysql:8.0
    container_name: flameletlab-api-mysql
    environment:
      MYSQL_DATABASE: flameletlab
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3310:3306"
    restart: always