name: deploy
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - master
      - main
jobs:
  flameletlab-api-app:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build application
        run: |
          ./mvnw -Pprod package -D skipTests=true
      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "target/flameletlab-api-0.0.1-SNAPSHOT.jar"
          target: "/tmp"
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            /etc/init.d/flameletlab-api stop
            mv /var/www/flameletlab-api.jar /var/www/flameletlab-api.old.jar
            mv /tmp/target/flameletlab-api-0.0.1-SNAPSHOT.jar /var/www/flameletlab-api.jar
            chown root:root /var/www/flameletlab-api.jar
            rm -rf /tmp/target
            rm -f /etc/init.d/flameletlab-api
            ln -s -f /var/www/flameletlab-api.jar /etc/init.d/flameletlab-api
            systemctl daemon-reload
            sudo /etc/init.d/flameletlab-api restart
            rm /var/www/flameletlab-api.old.jar